# Generated by Django 3.1.6 on 2021-02-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passby',
            field=models.CharField(max_length=20),
        ),
    ]
